import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import { Providers } from "./providers/ThemeProviders";
import AuthProvider from "./providers/AuthProvider";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`bg-gray-50 dark:bg-[#1b1b1f] flex flex-col min-h-[100vh] ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <Providers>
            <div className="m-0 flex flex-col justify-between">
              <Header/>
              <div className="main-Wrapper min-h-[45vh]">
                {children}
              </div>
              <Footer/>
            </div>
          </Providers>
        </AuthProvider>
      </body>
    </html>
  );
}
