import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import { Providers } from "./providers";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`bg-gray-50 dark:bg-[#1b1b1f] flex flex-col min-h-[100vh] ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <div className="max-w-[640px] md:max-w-[1536px] ml-auto mr-auto md:pl-20 md:pr-20">
            <Header/>
            {children}
            <Footer/>
          </div>
        </Providers>
      </body>
    </html>
  );
}
