import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import AuthProvider from "./providers/AuthProvider";
import { Toaster } from "react-hot-toast";
import { Providers } from "./providers/ThemeProviders";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Dev Blog",
  description: "blog website Generated by create next app, Next 15 ",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`bg-gray-50 dark:bg-[#1b1b1f] flex flex-col min-h-[100vh] ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <Providers>
              {children}
              <Toaster toastOptions={{style:{textAlign: "center"}}} />
            </Providers>
        </AuthProvider>
      </body>
    </html>
  );
}
